//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataResave_AQ.ServiceReference_AQ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppendAsyncStatus", Namespace="http://schemas.datacontract.org/2004/07/AquariusAcquisitionService.Dto")]
    [System.SerializableAttribute()]
    public partial class AppendAsyncStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumberOfPointsAppendedField;
        
        private int NumberOfPointsDeletedField;
        
        private string StatusField;
        
        private System.Guid UniqueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfPointsAppended {
            get {
                return this.NumberOfPointsAppendedField;
            }
            set {
                if ((this.NumberOfPointsAppendedField.Equals(value) != true)) {
                    this.NumberOfPointsAppendedField = value;
                    this.RaisePropertyChanged("NumberOfPointsAppended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfPointsDeleted {
            get {
                return this.NumberOfPointsDeletedField;
            }
            set {
                if ((this.NumberOfPointsDeletedField.Equals(value) != true)) {
                    this.NumberOfPointsDeletedField = value;
                    this.RaisePropertyChanged("NumberOfPointsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((this.UniqueIdField.Equals(value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterpolationType", Namespace="http://schemas.datacontract.org/2004/07/AquariusAcquisitionService")]
    public enum InterpolationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantaneousValues = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrecedingConstant = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrecedingTotals = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InstantaneousTotals = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DiscreteValues = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SucceedingConstant = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationDTO", Namespace="http://schemas.datacontract.org/2004/07/AquariusDataService")]
    [System.SerializableAttribute()]
    public partial class LocationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<float> ElevationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ElevationUnitsField;
        
        private string IdentifierField;
        
        private System.Nullable<float> LatitudeField;
        
        private string LocationNameField;
        
        private string LocationPathField;
        
        private string LocationTypeNameField;
        
        private System.Nullable<float> LongitudeField;
        
        private float UtcOffsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> ExtendedAttributesField;
        
        private System.Nullable<long> LocationIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Elevation {
            get {
                return this.ElevationField;
            }
            set {
                if ((this.ElevationField.Equals(value) != true)) {
                    this.ElevationField = value;
                    this.RaisePropertyChanged("Elevation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ElevationUnits {
            get {
                return this.ElevationUnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.ElevationUnitsField, value) != true)) {
                    this.ElevationUnitsField = value;
                    this.RaisePropertyChanged("ElevationUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationPath {
            get {
                return this.LocationPathField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationPathField, value) != true)) {
                    this.LocationPathField = value;
                    this.RaisePropertyChanged("LocationPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LocationTypeName {
            get {
                return this.LocationTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationTypeNameField, value) != true)) {
                    this.LocationTypeNameField = value;
                    this.RaisePropertyChanged("LocationTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<float> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float UtcOffset {
            get {
                return this.UtcOffsetField;
            }
            set {
                if ((this.UtcOffsetField.Equals(value) != true)) {
                    this.UtcOffsetField = value;
                    this.RaisePropertyChanged("UtcOffset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Collections.Generic.Dictionary<string, object> ExtendedAttributes {
            get {
                return this.ExtendedAttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedAttributesField, value) != true)) {
                    this.ExtendedAttributesField = value;
                    this.RaisePropertyChanged("ExtendedAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<long> LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_AQ.IAQAcquisitionService")]
    public interface IAQAcquisitionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAuthSession/GetAuthToken", ReplyAction="http://tempuri.org/IAQAuthSession/GetAuthTokenResponse")]
        string GetAuthToken(string user, string encodedPassword);
        
        // CODEGEN: 消息 IsConnectionValidRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAuthSession/IsConnectionValid", ReplyAction="http://tempuri.org/IAQAuthSession/IsConnectionValidResponse")]
        DataResave_AQ.ServiceReference_AQ.IsConnectionValidResponse IsConnectionValid(DataResave_AQ.ServiceReference_AQ.IsConnectionValidRequest request);
        
        // CODEGEN: 消息 KeepConnectionAliveRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAuthSession/KeepConnectionAlive", ReplyAction="http://tempuri.org/IAQAuthSession/KeepConnectionAliveResponse")]
        DataResave_AQ.ServiceReference_AQ.KeepConnectionAliveResponse KeepConnectionAlive(DataResave_AQ.ServiceReference_AQ.KeepConnectionAliveRequest request);
        
        // CODEGEN: 消息 AppendTimeSeriesAsyncRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/AppendTimeSeriesAsync", ReplyAction="http://tempuri.org/IAQAcquisitionService/AppendTimeSeriesAsyncResponse")]
        DataResave_AQ.ServiceReference_AQ.AppendTimeSeriesAsyncResponse AppendTimeSeriesAsync(DataResave_AQ.ServiceReference_AQ.AppendTimeSeriesAsyncRequest request);
        
        // CODEGEN: 消息 OverwriteAppendTimeSeriesAsyncRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/OverwriteAppendTimeSeriesAsync", ReplyAction="http://tempuri.org/IAQAcquisitionService/OverwriteAppendTimeSeriesAsyncResponse")]
        DataResave_AQ.ServiceReference_AQ.OverwriteAppendTimeSeriesAsyncResponse OverwriteAppendTimeSeriesAsync(DataResave_AQ.ServiceReference_AQ.OverwriteAppendTimeSeriesAsyncRequest request);
        
        // CODEGEN: 消息 GetAppendTimeSeriesAsyncStatusRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/GetAppendTimeSeriesAsyncStatus", ReplyAction="http://tempuri.org/IAQAcquisitionService/GetAppendTimeSeriesAsyncStatusResponse")]
        DataResave_AQ.ServiceReference_AQ.GetAppendTimeSeriesAsyncStatusResponse GetAppendTimeSeriesAsyncStatus(DataResave_AQ.ServiceReference_AQ.GetAppendTimeSeriesAsyncStatusRequest request);
        
        // CODEGEN: 消息 CreateTimeSeries3Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/CreateTimeSeries3", ReplyAction="http://tempuri.org/IAQAcquisitionService/CreateTimeSeries3Response")]
        DataResave_AQ.ServiceReference_AQ.CreateTimeSeries3Response CreateTimeSeries3(DataResave_AQ.ServiceReference_AQ.CreateTimeSeries3Request request);
        
        // CODEGEN: 消息 CreateLocationRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAQAcquisitionService/CreateLocation", ReplyAction="http://tempuri.org/IAQAcquisitionService/CreateLocationResponse")]
        DataResave_AQ.ServiceReference_AQ.CreateLocationResponse CreateLocation(DataResave_AQ.ServiceReference_AQ.CreateLocationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsConnectionValid", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsConnectionValidRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public string AQAuthToken;
        
        public IsConnectionValidRequest() {
        }
        
        public IsConnectionValidRequest(string AQAuthToken) {
            this.AQAuthToken = AQAuthToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsConnectionValidResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class IsConnectionValidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool IsConnectionValidResult;
        
        public IsConnectionValidResponse() {
        }
        
        public IsConnectionValidResponse(bool IsConnectionValidResult) {
            this.IsConnectionValidResult = IsConnectionValidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepConnectionAlive", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KeepConnectionAliveRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public string AQAuthToken;
        
        public KeepConnectionAliveRequest() {
        }
        
        public KeepConnectionAliveRequest(string AQAuthToken) {
            this.AQAuthToken = AQAuthToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KeepConnectionAliveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class KeepConnectionAliveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool KeepConnectionAliveResult;
        
        public KeepConnectionAliveResponse() {
        }
        
        public KeepConnectionAliveResponse(bool KeepConnectionAliveResult) {
            this.KeepConnectionAliveResult = KeepConnectionAliveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendTimeSeriesAsync", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendTimeSeriesAsyncRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public string AQAuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid uniqueId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte[] csvBytes;
        
        public AppendTimeSeriesAsyncRequest() {
        }
        
        public AppendTimeSeriesAsyncRequest(string AQAuthToken, System.Guid uniqueId, byte[] csvBytes) {
            this.AQAuthToken = AQAuthToken;
            this.uniqueId = uniqueId;
            this.csvBytes = csvBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendTimeSeriesAsyncResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendTimeSeriesAsyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AppendTimeSeriesAsyncResult;
        
        public AppendTimeSeriesAsyncResponse() {
        }
        
        public AppendTimeSeriesAsyncResponse(string AppendTimeSeriesAsyncResult) {
            this.AppendTimeSeriesAsyncResult = AppendTimeSeriesAsyncResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OverwriteAppendTimeSeriesAsync", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OverwriteAppendTimeSeriesAsyncRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public string AQAuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid uniqueId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string startTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string endTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] csvBytes;
        
        public OverwriteAppendTimeSeriesAsyncRequest() {
        }
        
        public OverwriteAppendTimeSeriesAsyncRequest(string AQAuthToken, System.Guid uniqueId, string startTime, string endTime, byte[] csvBytes) {
            this.AQAuthToken = AQAuthToken;
            this.uniqueId = uniqueId;
            this.startTime = startTime;
            this.endTime = endTime;
            this.csvBytes = csvBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OverwriteAppendTimeSeriesAsyncResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OverwriteAppendTimeSeriesAsyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string OverwriteAppendTimeSeriesAsyncResult;
        
        public OverwriteAppendTimeSeriesAsyncResponse() {
        }
        
        public OverwriteAppendTimeSeriesAsyncResponse(string OverwriteAppendTimeSeriesAsyncResult) {
            this.OverwriteAppendTimeSeriesAsyncResult = OverwriteAppendTimeSeriesAsyncResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppendTimeSeriesAsyncStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAppendTimeSeriesAsyncStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public string AQAuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string processToken;
        
        public GetAppendTimeSeriesAsyncStatusRequest() {
        }
        
        public GetAppendTimeSeriesAsyncStatusRequest(string AQAuthToken, string processToken) {
            this.AQAuthToken = AQAuthToken;
            this.processToken = processToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppendTimeSeriesAsyncStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAppendTimeSeriesAsyncStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataResave_AQ.ServiceReference_AQ.AppendAsyncStatus GetAppendTimeSeriesAsyncStatusResult;
        
        public GetAppendTimeSeriesAsyncStatusResponse() {
        }
        
        public GetAppendTimeSeriesAsyncStatusResponse(DataResave_AQ.ServiceReference_AQ.AppendAsyncStatus GetAppendTimeSeriesAsyncStatusResult) {
            this.GetAppendTimeSeriesAsyncStatusResult = GetAppendTimeSeriesAsyncStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTimeSeries3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTimeSeries3Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public string AQAuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string locationIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string parameterDisplayId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string unitId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public short utcOffsetMinutes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Nullable<System.TimeSpan> maximumGapInterval;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string methodCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public DataResave_AQ.ServiceReference_AQ.InterpolationType interpolationType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string subLocationIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string computationIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string computationPeriodIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public System.Nullable<bool> publish;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string comment;
        
        public CreateTimeSeries3Request() {
        }
        
        public CreateTimeSeries3Request(string AQAuthToken, string locationIdentifier, string label, string parameterDisplayId, string unitId, short utcOffsetMinutes, System.Nullable<System.TimeSpan> maximumGapInterval, string methodCode, DataResave_AQ.ServiceReference_AQ.InterpolationType interpolationType, string subLocationIdentifier, string computationIdentifier, string computationPeriodIdentifier, System.Nullable<bool> publish, string description, string comment) {
            this.AQAuthToken = AQAuthToken;
            this.locationIdentifier = locationIdentifier;
            this.label = label;
            this.parameterDisplayId = parameterDisplayId;
            this.unitId = unitId;
            this.utcOffsetMinutes = utcOffsetMinutes;
            this.maximumGapInterval = maximumGapInterval;
            this.methodCode = methodCode;
            this.interpolationType = interpolationType;
            this.subLocationIdentifier = subLocationIdentifier;
            this.computationIdentifier = computationIdentifier;
            this.computationPeriodIdentifier = computationPeriodIdentifier;
            this.publish = publish;
            this.description = description;
            this.comment = comment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTimeSeries3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTimeSeries3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid CreateTimeSeries3Result;
        
        public CreateTimeSeries3Response() {
        }
        
        public CreateTimeSeries3Response(System.Guid CreateTimeSeries3Result) {
            this.CreateTimeSeries3Result = CreateTimeSeries3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLocation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateLocationRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public string AQAuthToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DataResave_AQ.ServiceReference_AQ.LocationDTO location;
        
        public CreateLocationRequest() {
        }
        
        public CreateLocationRequest(string AQAuthToken, DataResave_AQ.ServiceReference_AQ.LocationDTO location) {
            this.AQAuthToken = AQAuthToken;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateLocationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long CreateLocationResult;
        
        public CreateLocationResponse() {
        }
        
        public CreateLocationResponse(long CreateLocationResult) {
            this.CreateLocationResult = CreateLocationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAQAcquisitionServiceChannel : DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AQAcquisitionServiceClient : System.ServiceModel.ClientBase<DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService>, DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService {
        
        public AQAcquisitionServiceClient() {
        }
        
        public AQAcquisitionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AQAcquisitionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AQAcquisitionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AQAcquisitionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAuthToken(string user, string encodedPassword) {
            return base.Channel.GetAuthToken(user, encodedPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataResave_AQ.ServiceReference_AQ.IsConnectionValidResponse DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService.IsConnectionValid(DataResave_AQ.ServiceReference_AQ.IsConnectionValidRequest request) {
            return base.Channel.IsConnectionValid(request);
        }
        
        public bool IsConnectionValid(string AQAuthToken) {
            DataResave_AQ.ServiceReference_AQ.IsConnectionValidRequest inValue = new DataResave_AQ.ServiceReference_AQ.IsConnectionValidRequest();
            inValue.AQAuthToken = AQAuthToken;
            DataResave_AQ.ServiceReference_AQ.IsConnectionValidResponse retVal = ((DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService)(this)).IsConnectionValid(inValue);
            return retVal.IsConnectionValidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataResave_AQ.ServiceReference_AQ.KeepConnectionAliveResponse DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService.KeepConnectionAlive(DataResave_AQ.ServiceReference_AQ.KeepConnectionAliveRequest request) {
            return base.Channel.KeepConnectionAlive(request);
        }
        
        public bool KeepConnectionAlive(string AQAuthToken) {
            DataResave_AQ.ServiceReference_AQ.KeepConnectionAliveRequest inValue = new DataResave_AQ.ServiceReference_AQ.KeepConnectionAliveRequest();
            inValue.AQAuthToken = AQAuthToken;
            DataResave_AQ.ServiceReference_AQ.KeepConnectionAliveResponse retVal = ((DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService)(this)).KeepConnectionAlive(inValue);
            return retVal.KeepConnectionAliveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataResave_AQ.ServiceReference_AQ.AppendTimeSeriesAsyncResponse DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService.AppendTimeSeriesAsync(DataResave_AQ.ServiceReference_AQ.AppendTimeSeriesAsyncRequest request) {
            return base.Channel.AppendTimeSeriesAsync(request);
        }
        
        public string AppendTimeSeriesAsync(string AQAuthToken, System.Guid uniqueId, byte[] csvBytes) {
            DataResave_AQ.ServiceReference_AQ.AppendTimeSeriesAsyncRequest inValue = new DataResave_AQ.ServiceReference_AQ.AppendTimeSeriesAsyncRequest();
            inValue.AQAuthToken = AQAuthToken;
            inValue.uniqueId = uniqueId;
            inValue.csvBytes = csvBytes;
            DataResave_AQ.ServiceReference_AQ.AppendTimeSeriesAsyncResponse retVal = ((DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService)(this)).AppendTimeSeriesAsync(inValue);
            return retVal.AppendTimeSeriesAsyncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataResave_AQ.ServiceReference_AQ.OverwriteAppendTimeSeriesAsyncResponse DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService.OverwriteAppendTimeSeriesAsync(DataResave_AQ.ServiceReference_AQ.OverwriteAppendTimeSeriesAsyncRequest request) {
            return base.Channel.OverwriteAppendTimeSeriesAsync(request);
        }
        
        public string OverwriteAppendTimeSeriesAsync(string AQAuthToken, System.Guid uniqueId, string startTime, string endTime, byte[] csvBytes) {
            DataResave_AQ.ServiceReference_AQ.OverwriteAppendTimeSeriesAsyncRequest inValue = new DataResave_AQ.ServiceReference_AQ.OverwriteAppendTimeSeriesAsyncRequest();
            inValue.AQAuthToken = AQAuthToken;
            inValue.uniqueId = uniqueId;
            inValue.startTime = startTime;
            inValue.endTime = endTime;
            inValue.csvBytes = csvBytes;
            DataResave_AQ.ServiceReference_AQ.OverwriteAppendTimeSeriesAsyncResponse retVal = ((DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService)(this)).OverwriteAppendTimeSeriesAsync(inValue);
            return retVal.OverwriteAppendTimeSeriesAsyncResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataResave_AQ.ServiceReference_AQ.GetAppendTimeSeriesAsyncStatusResponse DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService.GetAppendTimeSeriesAsyncStatus(DataResave_AQ.ServiceReference_AQ.GetAppendTimeSeriesAsyncStatusRequest request) {
            return base.Channel.GetAppendTimeSeriesAsyncStatus(request);
        }
        
        public DataResave_AQ.ServiceReference_AQ.AppendAsyncStatus GetAppendTimeSeriesAsyncStatus(string AQAuthToken, string processToken) {
            DataResave_AQ.ServiceReference_AQ.GetAppendTimeSeriesAsyncStatusRequest inValue = new DataResave_AQ.ServiceReference_AQ.GetAppendTimeSeriesAsyncStatusRequest();
            inValue.AQAuthToken = AQAuthToken;
            inValue.processToken = processToken;
            DataResave_AQ.ServiceReference_AQ.GetAppendTimeSeriesAsyncStatusResponse retVal = ((DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService)(this)).GetAppendTimeSeriesAsyncStatus(inValue);
            return retVal.GetAppendTimeSeriesAsyncStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataResave_AQ.ServiceReference_AQ.CreateTimeSeries3Response DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService.CreateTimeSeries3(DataResave_AQ.ServiceReference_AQ.CreateTimeSeries3Request request) {
            return base.Channel.CreateTimeSeries3(request);
        }
        
        public System.Guid CreateTimeSeries3(string AQAuthToken, string locationIdentifier, string label, string parameterDisplayId, string unitId, short utcOffsetMinutes, System.Nullable<System.TimeSpan> maximumGapInterval, string methodCode, DataResave_AQ.ServiceReference_AQ.InterpolationType interpolationType, string subLocationIdentifier, string computationIdentifier, string computationPeriodIdentifier, System.Nullable<bool> publish, string description, string comment) {
            DataResave_AQ.ServiceReference_AQ.CreateTimeSeries3Request inValue = new DataResave_AQ.ServiceReference_AQ.CreateTimeSeries3Request();
            inValue.AQAuthToken = AQAuthToken;
            inValue.locationIdentifier = locationIdentifier;
            inValue.label = label;
            inValue.parameterDisplayId = parameterDisplayId;
            inValue.unitId = unitId;
            inValue.utcOffsetMinutes = utcOffsetMinutes;
            inValue.maximumGapInterval = maximumGapInterval;
            inValue.methodCode = methodCode;
            inValue.interpolationType = interpolationType;
            inValue.subLocationIdentifier = subLocationIdentifier;
            inValue.computationIdentifier = computationIdentifier;
            inValue.computationPeriodIdentifier = computationPeriodIdentifier;
            inValue.publish = publish;
            inValue.description = description;
            inValue.comment = comment;
            DataResave_AQ.ServiceReference_AQ.CreateTimeSeries3Response retVal = ((DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService)(this)).CreateTimeSeries3(inValue);
            return retVal.CreateTimeSeries3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataResave_AQ.ServiceReference_AQ.CreateLocationResponse DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService.CreateLocation(DataResave_AQ.ServiceReference_AQ.CreateLocationRequest request) {
            return base.Channel.CreateLocation(request);
        }
        
        public long CreateLocation(string AQAuthToken, DataResave_AQ.ServiceReference_AQ.LocationDTO location) {
            DataResave_AQ.ServiceReference_AQ.CreateLocationRequest inValue = new DataResave_AQ.ServiceReference_AQ.CreateLocationRequest();
            inValue.AQAuthToken = AQAuthToken;
            inValue.location = location;
            DataResave_AQ.ServiceReference_AQ.CreateLocationResponse retVal = ((DataResave_AQ.ServiceReference_AQ.IAQAcquisitionService)(this)).CreateLocation(inValue);
            return retVal.CreateLocationResult;
        }
    }
}
